# Generated by Django 5.0.6 on 2024-07-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPersonnel', models.CharField(max_length=100, null=True)),
                ('PrenomPersonnel', models.CharField(max_length=100, null=True)),
                ('EmailPersonnel', models.EmailField(max_length=100, null=True)),
                ('NomAgence', models.CharField(choices=[('CASABLANACA', 'CASABLANACA'), ('TANGER', 'TANGER')], max_length=100, null=True)),
                ('Tel', models.CharField(max_length=15, null=True)),
                ('Adresse', models.CharField(max_length=100, null=True)),
                ('DateEumbauche', models.DateField(null=True)),
                ('Departement', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
