# Generated by Django 5.0.6 on 2024-07-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Adresse',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='DateEumbauche',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Departement',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='EmailPersonnel',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Tel',
        ),
        migrations.AddField(
            model_name='staff',
            name='NumImma',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
