# Generated by Django 5.0.6 on 2024-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0002_remove_staff_adresse_remove_staff_dateeumbauche_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumInventaire', models.CharField(max_length=100, null=True)),
                ('Type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Ecran', 'Ecran'), ('Imprimante laser', 'Imprimante laser'), ('Imprimante thermique', 'Imprimante thermique'), ('PDA', 'PDA')], max_length=100, null=True)),
                ('NumSerie', models.CharField(max_length=100, null=True)),
                ('Hostname', models.CharField(max_length=100, null=True)),
                ('Marque', models.CharField(max_length=100, null=True)),
                ('Modele', models.CharField(max_length=100, null=True)),
                ('DateAchat', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='staff',
        ),
    ]
