# Generated by Django 5.0.6 on 2024-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0003_materiel_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumImmatriculatione', models.CharField(max_length=100, null=True)),
                ('Nom', models.CharField(max_length=100, null=True)),
                ('Prenom', models.CharField(max_length=100, null=True)),
                ('Agence', models.CharField(choices=[('CASABLANCA', 'CASABLANCA'), ('TANGER', 'TANGER')], max_length=100, null=True)),
                ('Service', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
