# Generated by Django 5.0.6 on 2024-07-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0004_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff',
        ),
    ]
