# Generated by Django 5.0.6 on 2024-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Agence',
            field=models.CharField(choices=[('CASABLANCA', 'CASABLANCA'), ('TANGER', 'TANGER')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='NumImmatriculatione',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
